name: PhiO CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.9", "3.10", "3.11" ]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install pytest

      - name: Make scripts executable
        run: |
          chmod +x *.sh 2>/dev/null || true
          chmod +x scripts/*.sh 2>/dev/null || true
          chmod +x tests/*.sh 2>/dev/null || true

      - name: Final validation (contract)
        env:
          PHIO_INSTRUMENT: ./phi_otimes_o_instrument_v0_1.py
          PYTHONPATH: .
        run: |
          bash final_validation.sh

      - name: Run pytest
        env:
          PHIO_INSTRUMENT: ./phi_otimes_o_instrument_v0_1.py
          PYTHONPATH: .
        run: |
          python -m pytest -q

      - name: Run traceability checks
        run: |
          bash tests/test_traceability.sh

      - name: Run collector max tests
        run: |
          bash run_collector_tests.sh
